[cf_custom]
category = "dev"
level = 6
state = "working"
url = "https://github.com/computablefacts/cf_custom_ynh"

[jenkins]
category = "dev"
level = 6
state = "working"
url = "https://github.com/computablefacts/jenkins_ynh"
branch = "cf-prod"

[portainer]
category = "dev"
level = 6
state = "working"
url = "https://github.com/computablefacts/portainer_ynh"

[redirect]
category = "dev"
level = 6
state = "inprogress"
url = "https://github.com/computablefacts/redirect_ynh"
branch = "cf-prod"

# TODO: add cf_faq
